// Generated by gencpp from file evologics_ros_sync/EvologicsSyncDiagnostics.msg
// DO NOT EDIT!


#ifndef EVOLOGICS_ROS_SYNC_MESSAGE_EVOLOGICSSYNCDIAGNOSTICS_H
#define EVOLOGICS_ROS_SYNC_MESSAGE_EVOLOGICSSYNCDIAGNOSTICS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace evologics_ros_sync
{
template <class ContainerAllocator>
struct EvologicsSyncDiagnostics_
{
  typedef EvologicsSyncDiagnostics_<ContainerAllocator> Type;

  EvologicsSyncDiagnostics_()
    : header()
    , ack_received(false)
    , pbm_received(false)
    , ul_received(false)
    , position_estimated(false)  {
    }
  EvologicsSyncDiagnostics_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ack_received(false)
    , pbm_received(false)
    , ul_received(false)
    , position_estimated(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _ack_received_type;
  _ack_received_type ack_received;

   typedef uint8_t _pbm_received_type;
  _pbm_received_type pbm_received;

   typedef uint8_t _ul_received_type;
  _ul_received_type ul_received;

   typedef uint8_t _position_estimated_type;
  _position_estimated_type position_estimated;




  typedef boost::shared_ptr< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> const> ConstPtr;

}; // struct EvologicsSyncDiagnostics_

typedef ::evologics_ros_sync::EvologicsSyncDiagnostics_<std::allocator<void> > EvologicsSyncDiagnostics;

typedef boost::shared_ptr< ::evologics_ros_sync::EvologicsSyncDiagnostics > EvologicsSyncDiagnosticsPtr;
typedef boost::shared_ptr< ::evologics_ros_sync::EvologicsSyncDiagnostics const> EvologicsSyncDiagnosticsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace evologics_ros_sync

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'evologics_ros_sync': ['/home/antoni/robot_ws/src/evologics_ros_sync/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'auv_msgs': ['/home/antoni/workspace/catkin_ws/src/turbot_stack/auv_msgs/msg', '/home/antoni/workspace/catkin_ws/devel/share/auv_msgs/msg'], 'diagnostic_msgs': ['/opt/ros/kinetic/share/diagnostic_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d64d07ba28a599743c61be9366dad22b";
  }

  static const char* value(const ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd64d07ba28a59974ULL;
  static const uint64_t static_value2 = 0x3c61be9366dad22bULL;
};

template<class ContainerAllocator>
struct DataType< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "evologics_ros_sync/EvologicsSyncDiagnostics";
  }

  static const char* value(const ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# message containing USBL data published by modem driver\n\
\n\
Header header                           # message header which contains current timestamp\n\
\n\
bool ack_received						# True if aknowledgement from modem has been received\n\
bool pbm_received						# True if piggyback mssage from modem has been received\n\
bool ul_received						# True if the relative modem position has been estimated\n\
bool position_estimated					# True if the absoulte position has been estimated\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ack_received);
      stream.next(m.pbm_received);
      stream.next(m.ul_received);
      stream.next(m.position_estimated);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EvologicsSyncDiagnostics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::evologics_ros_sync::EvologicsSyncDiagnostics_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ack_received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ack_received);
    s << indent << "pbm_received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pbm_received);
    s << indent << "ul_received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ul_received);
    s << indent << "position_estimated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.position_estimated);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVOLOGICS_ROS_SYNC_MESSAGE_EVOLOGICSSYNCDIAGNOSTICS_H
