// Generated by gencpp from file evologics_ros_sync/EvologicsUsbllong.msg
// DO NOT EDIT!


#ifndef EVOLOGICS_ROS_SYNC_MESSAGE_EVOLOGICSUSBLLONG_H
#define EVOLOGICS_ROS_SYNC_MESSAGE_EVOLOGICSUSBLLONG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace evologics_ros_sync
{
template <class ContainerAllocator>
struct EvologicsUsbllong_
{
  typedef EvologicsUsbllong_<ContainerAllocator> Type;

  EvologicsUsbllong_()
    : header()
    , remote_address(0)
    , X(0.0)
    , Y(0.0)
    , Z(0.0)
    , N(0.0)
    , E(0.0)
    , D(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , rssi(0.0)
    , integrity(0.0)
    , accuracy(0.0)  {
    }
  EvologicsUsbllong_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , remote_address(0)
    , X(0.0)
    , Y(0.0)
    , Z(0.0)
    , N(0.0)
    , E(0.0)
    , D(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , rssi(0.0)
    , integrity(0.0)
    , accuracy(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _remote_address_type;
  _remote_address_type remote_address;

   typedef float _X_type;
  _X_type X;

   typedef float _Y_type;
  _Y_type Y;

   typedef float _Z_type;
  _Z_type Z;

   typedef float _N_type;
  _N_type N;

   typedef float _E_type;
  _E_type E;

   typedef float _D_type;
  _D_type D;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _rssi_type;
  _rssi_type rssi;

   typedef float _integrity_type;
  _integrity_type integrity;

   typedef float _accuracy_type;
  _accuracy_type accuracy;




  typedef boost::shared_ptr< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> const> ConstPtr;

}; // struct EvologicsUsbllong_

typedef ::evologics_ros_sync::EvologicsUsbllong_<std::allocator<void> > EvologicsUsbllong;

typedef boost::shared_ptr< ::evologics_ros_sync::EvologicsUsbllong > EvologicsUsbllongPtr;
typedef boost::shared_ptr< ::evologics_ros_sync::EvologicsUsbllong const> EvologicsUsbllongConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace evologics_ros_sync

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'evologics_ros_sync': ['/home/antoni/robot_ws/src/evologics_ros_sync/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'auv_msgs': ['/home/antoni/workspace/catkin_ws/src/turbot_stack/auv_msgs/msg', '/home/antoni/workspace/catkin_ws/devel/share/auv_msgs/msg'], 'diagnostic_msgs': ['/opt/ros/kinetic/share/diagnostic_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> >
{
  static const char* value()
  {
    return "926a7508803471db6934cecbabe54e0e";
  }

  static const char* value(const ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x926a7508803471dbULL;
  static const uint64_t static_value2 = 0x6934cecbabe54e0eULL;
};

template<class ContainerAllocator>
struct DataType< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> >
{
  static const char* value()
  {
    return "evologics_ros_sync/EvologicsUsbllong";
  }

  static const char* value(const ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# message containing USBL data published by modem driver\n\
\n\
Header header                           # message header which contains current timestamp\n\
\n\
uint8 remote_address					# The target's address\n\
\n\
float32 X                               # X coordinate of the target in the local device's reference frame in metres\n\
float32 Y                               # Y coordinate of the target in the local device's reference frame in metres\n\
float32 Z                               # Z coordinate of the target in the local device's reference frame in metres\n\
\n\
float32 N                               # N coordinate of the target in the local device's reference frame in metres\n\
float32 E                               # E coordinate of the target in the local device's reference frame in metres\n\
float32 D                               # D coordinate of the target in the local device's reference frame in metres\n\
\n\
float32 roll                            # rotation angles of the local device, in radians, floating point\n\
float32 pitch\n\
float32 yaw\n\
\n\
float32 rssi                        	# Received Signal Strength Indicator (admisible if values lie in between -20dB and -85dB)\n\
float32 integrity                       # Signal integrity level (weak if below 100)\n\
float32 accuracy 						# Accuracy of the position fix, in radians.\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.remote_address);
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.Z);
      stream.next(m.N);
      stream.next(m.E);
      stream.next(m.D);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.rssi);
      stream.next(m.integrity);
      stream.next(m.accuracy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EvologicsUsbllong_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::evologics_ros_sync::EvologicsUsbllong_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "remote_address: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_address);
    s << indent << "X: ";
    Printer<float>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<float>::stream(s, indent + "  ", v.Y);
    s << indent << "Z: ";
    Printer<float>::stream(s, indent + "  ", v.Z);
    s << indent << "N: ";
    Printer<float>::stream(s, indent + "  ", v.N);
    s << indent << "E: ";
    Printer<float>::stream(s, indent + "  ", v.E);
    s << indent << "D: ";
    Printer<float>::stream(s, indent + "  ", v.D);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "rssi: ";
    Printer<float>::stream(s, indent + "  ", v.rssi);
    s << indent << "integrity: ";
    Printer<float>::stream(s, indent + "  ", v.integrity);
    s << indent << "accuracy: ";
    Printer<float>::stream(s, indent + "  ", v.accuracy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EVOLOGICS_ROS_SYNC_MESSAGE_EVOLOGICSUSBLLONG_H
