(cl:defpackage evologics_ros_sync-msg
  (:use )
  (:export
   "<EVOLOGICSCHANNELDIAGNOSTICS>"
   "EVOLOGICSCHANNELDIAGNOSTICS"
   "<EVOLOGICSSYNCDIAGNOSTICS>"
   "EVOLOGICSSYNCDIAGNOSTICS"
   "<EVOLOGICSUSBLLONG>"
   "EVOLOGICSUSBLLONG"
  ))

