(cl:in-package evologics_ros_sync-msg)
(cl:export '(HEADER-VAL
          HEADER
          REMOTE_ADDRESS-VAL
          REMOTE_ADDRESS
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          N-VAL
          N
          E-VAL
          E
          D-VAL
          D
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          RSSI-VAL
          RSSI
          INTEGRITY-VAL
          INTEGRITY
          ACCURACY-VAL
          ACCURACY
))